# Generated by Django 4.2 on 2025-04-28 20:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='document',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
