# Generated by Django 4.2.7 on 2025-05-16 10:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_document_alter_article_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='photo',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Maqola matni'),
        ),
        migrations.AlterField(
            model_name='article',
            name='document',
            field=models.FileField(upload_to='media/', verbose_name='fayl yuklash'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=200, verbose_name='Annotatsiya'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Maqola nomi'),
        ),
    ]
